#CA_15mM_1264_Box_30 run1 CA_15mM_1264_Box_30 run2 CA_15mM_1264_Box_30 run3 CA_15mM_1264_Box_50 run1 CA_15mM_1264_Box_50 run2 CA_15mM_1264_Box_50 run3
#MG_15mM_1264_Box_30 run1 MG_15mM_1264_Box_30 run2 MG_15mM_1264_Box_30 run3 MG_15mM_1264_Box_50 run1 MG_15mM_1264_Box_50 run2 MG_15mM_1264_Box_50 run3
#NaCl_Box_30 run1 NaCl_Box_30 run2 NaCl_Box_30 run3 NaCl_Box_50 run1 NaCl_Box_50 run2 NaCl_Box_50 run3
foreach {name run} {K63E run1 K63E run2 K63E run3 K74N run1 K74N run2 K74N run3 R78H run1 R78H run2 R78H run3 S57P run1 S57P run2 S57P run3 S103F run1 S103F run2 S103F run3 wild run1 wild run2 wild run3} {

mol load parm7 ../${name}_rw.prmtop
mol addfile ../${name}_${run}_rw.nc first 2500 last 25000 step 10 waitfor all
source rename_chainID_with_tail.tcl


set nframes [expr  [molinfo top get numframes] - 1 ]
puts "$nframes"
	
#Align the alpha helix core ti the start structre
set alpha_core_ca "((segname CHA CHE and (resid 8 to 21 or resid 27 to 41 or resid 49 to 78 or resid 84 to 96)) or (segname CHB CHF and (resid 5 to 22 or resid 30 to 57 or resid 63 to 74))  or (segname CHC CHG and (resid 7 to 13 or resid 17 to 28 or resid 36 to 64 or resid 70 to 88 or resid 103 to 107)) or (segname CHD CHH and (resid 8 to 20 or resid 26 to 55 or resid 61 to 94))) or (segname CHU and (resid 4 to 17 or resid 17 to 24 or resid 37 to 55))  and name CA"


set frame0_alpha_core_ca [atomselect top $alpha_core_ca frame 0]
set sel_alpha_core_ca [atomselect top $alpha_core_ca]

set all [atomselect top "all"]

for { set i 1 } { $i<$nframes } { incr i } {

$sel_alpha_core_ca frame $i
$all frame $i
set trans_mat [measure fit $sel_alpha_core_ca $frame0_alpha_core_ca]
$all move $trans_mat
}

set rmsf [measure rmsf $all first 1 last 2250]
# set rmsf [measure rmsf $all first 9000 last 10000]

$all frame $nframes
# was 10001
$all set beta $rmsf
#$all writepdb ./rmsf/${name}_nucl_rmsf.pdb

#let's do some file output
set chains [list CHU]
set chains_names [list H1]


set outfile [open ./${name}_${run}_rmsf_chains.dat w]
puts $outfile "RMSF of CA or P atoms of nucleosome"
puts $outfile "Generated by VMD rmsf"
puts $outfile "Residue ID"
puts $outfile "RMSF, A"


set ts "Resid"
foreach segname  $chains_names {
append ts "\t$segname"
}
puts $outfile $ts

for  { set i 1 } { $i<=75 } { incr i } {
set ds "$i"
foreach seg  $chains {

set sel [atomselect top "segname $seg and name CA P and resid '$i' "]
if {[$sel num] == 0} { set beta 0
} else {
set  beta [$sel get beta]
}

append ds "\t$beta"

}
puts $outfile $ds
}

close $outfile 


set outfile [open ./${name}_${run}_rmsf_chains_sch.dat w]
puts $outfile "Average RMSF of side chains and bases atoms of nucleosome"
puts $outfile "Generated by VMD rmsf"
puts $outfile "Residue ID"
puts $outfile "RMSF, A"


set ts "Resid"
foreach segname  $chains_names {
append ts "\t$segname"
}
puts $outfile $ts

for  { set i 1 } { $i<=75 } { incr i } {
set ds "$i"
foreach seg  $chains {
# set sel [atomselect top "segname $seg and (not backbone) and resid '$i' and noh"]
set sel [atomselect top "segname $seg and (not backbone) and (not name P O1P O2P O3' O5' C5' C1' C2' C3' C4' O4') and resid '$i' and noh"]
if {[$sel num] == 0} { set mean 0
} else {
set  beta [$sel get beta]
set bl [llength $beta]
set mean 0
for {set j 0} { $j<$bl } { incr j } {
set mean [expr $mean + [lindex $beta $j]]
}
set mean [expr $mean / $bl]
}


append ds "\t$mean"

}
puts $outfile $ds
}

close $outfile 

}
exit
